import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
test('paragraph integrity notes disclose detector limitations and preserve earlier releases', () => {
  const html = readFileSync(new URL('../pages/admin.html', import.meta.url), 'utf8');
  assert.match(html, /휴머나이징 v2\.5\.77 · AI 감지 v1\.44/);
  assert.match(html, /v2\.5\.74 · 감지 v1\.43/);
  assert.match(html, /113건은 개발·회귀 자료/);
  const timeline = html.split('<div class="gp-admin-patch-timeline">')[1];
  const current = timeline.split('</details>')[0];
  assert.match(current, /v2\.5\.77/);
  assert.match(current, /Backend 7a914dd/);
  assert.match(current, /2,263개/);
  assert.match(current, /두 번째의 정도 표현 누락은 실패/);
  assert.match(current, /새로운 모델 호출 단계·수리 반복·차단 정책은 추가하지 않았고/);
  assert.ok(timeline.indexOf('v2.5.77') < timeline.indexOf('v2.5.76'));
  assert.ok(timeline.indexOf('v2.5.76') < timeline.indexOf('v2.5.75'));
  assert.match(timeline, /점수 산식과 이력 보정은 그대로/);
  assert.match(timeline, /세 번째 전체 신규 생성은 하지 않았으며/);
  const latest = timeline.split('<span class="gp-admin-patch-version">v2.5.74')[1].split('</details>')[0];
  assert.match(latest, /gp-admin-patch-state is-live">운영 반영/);
  assert.match(latest, /백엔드 2,160개, 프런트 348개/);
  assert.match(latest, /전량 신규 생성은 아닙니다/);
  assert.match(latest, /일부 진단 오탐/);
  assert.doesNotMatch(latest, /배포 보류|진행 중/);
  assert.match(html, /원문·결과 97쌍 전문 대조/);
  assert.match(html, /사람 블라인드 평가, 감지 정확도 또는 전체 문장 품질의 무오류 보장은 아닙니다/);
  assert.match(html, /Backend dc3ae90/);
  assert.match(html, /Backend b0b8efd/);
  assert.match(html, /해결 완료로 표시하지 않습니다/);
  assert.match(html, /Backend 23a3624/);
  const count = [...html.matchAll(/<details class="gp-admin-patch-release"/g)].length;
  assert.equal(count, 89);
  assert.match(html, /89개 변경 묶음/);
  assert.match(html, /Backend 80e7543/);
  assert.match(html, /원본 PDF 대조가 없는 상태/);
  assert.match(html, /페이지 간 논리적 행 복원/);
  assert.match(html, /대표 본문 12개/);
  assert.match(html, /미시도 조각 수/);
  assert.match(html, /신규 유료 모델 재실행은 하지 않았으며/);
  assert.match(html, /v2\.5\.53 · 감지 v1\.34/);
  assert.match(html, /실패 응답과 채택하지 않은 후보/);
});
